
export interface CountryData {
  name: string;
  code: string;
  phoneCode: string;
  currency: string;
}

export const COUNTRIES: CountryData[] = [
  { name: 'Afrique du Sud', code: 'ZA', phoneCode: '+27', currency: 'ZAR' },
  { name: 'Algérie', code: 'DZ', phoneCode: '+213', currency: 'DZD' },
  { name: 'Angola', code: 'AO', phoneCode: '+244', currency: 'AOA' },
  { name: 'Bénin', code: 'BJ', phoneCode: '+229', currency: 'XOF' },
  { name: 'Botswana', code: 'BW', phoneCode: '+267', currency: 'BWP' },
  { name: 'Burkina Faso', code: 'BF', phoneCode: '+226', currency: 'XOF' },
  { name: 'Burundi', code: 'BI', phoneCode: '+257', currency: 'BIF' },
  { name: 'Cameroun', code: 'CM', phoneCode: '+237', currency: 'XAF' },
  { name: 'Cap-Vert', code: 'CV', phoneCode: '+238', currency: 'CVE' },
  { name: 'Centrafrique', code: 'CF', phoneCode: '+236', currency: 'XAF' },
  { name: 'Comores', code: 'KM', phoneCode: '+269', currency: 'KMF' },
  { name: 'Congo', code: 'CG', phoneCode: '+242', currency: 'XAF' },
  { name: 'Côte d\'Ivoire', code: 'CI', phoneCode: '+225', currency: 'XOF' },
  { name: 'Djibouti', code: 'DJ', phoneCode: '+253', currency: 'DJF' },
  { name: 'Égypte', code: 'EG', phoneCode: '+20', currency: 'EGP' },
  { name: 'Érythrée', code: 'ER', phoneCode: '+291', currency: 'ERN' },
  { name: 'Eswatini', code: 'SZ', phoneCode: '+268', currency: 'SZL' },
  { name: 'Éthiopie', code: 'ET', phoneCode: '+251', currency: 'ETB' },
  { name: 'Gabon', code: 'GA', phoneCode: '+241', currency: 'XAF' },
  { name: 'Gambie', code: 'GM', phoneCode: '+220', currency: 'GMD' },
  { name: 'Ghana', code: 'GH', phoneCode: '+233', currency: 'GHS' },
  { name: 'Guinée', code: 'GN', phoneCode: '+224', currency: 'GNF' },
  { name: 'Guinée-Bissau', code: 'GW', phoneCode: '+245', currency: 'XOF' },
  { name: 'Guinée équatoriale', code: 'GQ', phoneCode: '+240', currency: 'XAF' },
  { name: 'Kenya', code: 'KE', phoneCode: '+254', currency: 'KES' },
  { name: 'Lesotho', code: 'LS', phoneCode: '+266', currency: 'LSL' },
  { name: 'Libéria', code: 'LR', phoneCode: '+231', currency: 'LRD' },
  { name: 'Libye', code: 'LY', phoneCode: '+218', currency: 'LYD' },
  { name: 'Madagascar', code: 'MG', phoneCode: '+261', currency: 'MGA' },
  { name: 'Malawi', code: 'MW', phoneCode: '+265', currency: 'MWK' },
  { name: 'Mali', code: 'ML', phoneCode: '+223', currency: 'XOF' },
  { name: 'Maroc', code: 'MA', phoneCode: '+212', currency: 'MAD' },
  { name: 'Maurice', code: 'MU', phoneCode: '+230', currency: 'MUR' },
  { name: 'Mauritanie', code: 'MR', phoneCode: '+222', currency: 'MRU' },
  { name: 'Mozambique', code: 'MZ', phoneCode: '+258', currency: 'MZN' },
  { name: 'Namibie', code: 'NA', phoneCode: '+264', currency: 'NAD' },
  { name: 'Niger', code: 'NE', phoneCode: '+227', currency: 'XOF' },
  { name: 'Nigeria', code: 'NG', phoneCode: '+234', currency: 'NGN' },
  { name: 'Ouganda', code: 'UG', phoneCode: '+256', currency: 'UGX' },
  { name: 'République démocratique du Congo', code: 'CD', phoneCode: '+243', currency: 'CDF' },
  { name: 'Rwanda', code: 'RW', phoneCode: '+250', currency: 'RWF' },
  { name: 'São Tomé-et-Príncipe', code: 'ST', phoneCode: '+239', currency: 'STN' },
  { name: 'Sénégal', code: 'SN', phoneCode: '+221', currency: 'XOF' },
  { name: 'Seychelles', code: 'SC', phoneCode: '+248', currency: 'SCR' },
  { name: 'Sierra Leone', code: 'SL', phoneCode: '+232', currency: 'SLL' },
  { name: 'Somalie', code: 'SO', phoneCode: '+252', currency: 'SOS' },
  { name: 'Soudan', code: 'SD', phoneCode: '+249', currency: 'SDG' },
  { name: 'Soudan du Sud', code: 'SS', phoneCode: '+211', currency: 'SSP' },
  { name: 'Tanzanie', code: 'TZ', phoneCode: '+255', currency: 'TZS' },
  { name: 'Tchad', code: 'TD', phoneCode: '+235', currency: 'XAF' },
  { name: 'Togo', code: 'TG', phoneCode: '+228', currency: 'XOF' },
  { name: 'Tunisie', code: 'TN', phoneCode: '+216', currency: 'TND' },
  { name: 'Zambie', code: 'ZM', phoneCode: '+260', currency: 'ZMW' },
  { name: 'Zimbabwe', code: 'ZW', phoneCode: '+263', currency: 'ZWL' },
];

export const getCountryByName = (countryName: string): CountryData | undefined => {
  return COUNTRIES.find(country => country.name === countryName);
};

export const CURRENCIES = [
  { code: 'XOF', name: 'Franc CFA BCEAO (XOF)' },
  { code: 'XAF', name: 'Franc CFA BEAC (XAF)' },
  { code: 'EUR', name: 'Euro (EUR)' },
  { code: 'USD', name: 'Dollar américain (USD)' },
  { code: 'ZAR', name: 'Rand sud-africain (ZAR)' },
  { code: 'DZD', name: 'Dinar algérien (DZD)' },
  { code: 'AOA', name: 'Kwanza angolais (AOA)' },
  { code: 'BWP', name: 'Pula botswanais (BWP)' },
  { code: 'BIF', name: 'Franc burundais (BIF)' },
  { code: 'CVE', name: 'Escudo cap-verdien (CVE)' },
  { code: 'KMF', name: 'Franc comorien (KMF)' },
  { code: 'DJF', name: 'Franc djiboutien (DJF)' },
  { code: 'EGP', name: 'Livre égyptienne (EGP)' },
  { code: 'ERN', name: 'Nakfa érythréen (ERN)' },
  { code: 'SZL', name: 'Lilangeni swazi (SZL)' },
  { code: 'ETB', name: 'Birr éthiopien (ETB)' },
  { code: 'GMD', name: 'Dalasi gambien (GMD)' },
  { code: 'GHS', name: 'Cedi ghanéen (GHS)' },
  { code: 'GNF', name: 'Franc guinéen (GNF)' },
  { code: 'KES', name: 'Shilling kényan (KES)' },
  { code: 'LSL', name: 'Loti lesothan (LSL)' },
  { code: 'LRD', name: 'Dollar libérien (LRD)' },
  { code: 'LYD', name: 'Dinar libyen (LYD)' },
  { code: 'MGA', name: 'Ariary malgache (MGA)' },
  { code: 'MWK', name: 'Kwacha malawien (MWK)' },
  { code: 'MAD', name: 'Dirham marocain (MAD)' },
  { code: 'MUR', name: 'Roupie mauricienne (MUR)' },
  { code: 'MRU', name: 'Ouguiya mauritanien (MRU)' },
  { code: 'MZN', name: 'Metical mozambicain (MZN)' },
  { code: 'NAD', name: 'Dollar namibien (NAD)' },
  { code: 'NGN', name: 'Naira nigérien (NGN)' },
  { code: 'UGX', name: 'Shilling ougandais (UGX)' },
  { code: 'CDF', name: 'Franc congolais (CDF)' },
  { code: 'RWF', name: 'Franc rwandais (RWF)' },
  { code: 'STN', name: 'Dobra santoméen (STN)' },
  { code: 'SCR', name: 'Roupie seychelloise (SCR)' },
  { code: 'SLL', name: 'Leone sierra-léonais (SLL)' },
  { code: 'SOS', name: 'Shilling somalien (SOS)' },
  { code: 'SDG', name: 'Livre soudanaise (SDG)' },
  { code: 'SSP', name: 'Livre sud-soudanaise (SSP)' },
  { code: 'TZS', name: 'Shilling tanzanien (TZS)' },
  { code: 'TND', name: 'Dinar tunisien (TND)' },
  { code: 'ZMW', name: 'Kwacha zambien (ZMW)' },
  { code: 'ZWL', name: 'Dollar zimbabwéen (ZWL)' },
];
