// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jpmpfpeuqutzfcdlhvpi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpwbXBmcGV1cXV0emZjZGxodnBpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2NDQ1NzEsImV4cCI6MjA2NTIyMDU3MX0.MfzWcBEhr927vSlR5Lbl2APjg5-e0WgmB0sXyQxRYhg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);